#run 'docker compose up --build' to show changes by rebuilding images
services:
  backend:
    build: ./backend
    volumes:
      - type: bind
        source: ./backend/src
        target: /app/src
    env_file:
      - backend/variables.env
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    volumes:
      - type: bind
        source: ./frontend
        target: /app/src
    command: "npx vite --host 0.0.0.0"
    ports:
     - "5173:5173"
    