#run 'docker compose up --build' to show changes by rebuilding images
services:
  flask:
    build: ./backend
    volumes:
      - type: bind
        source: ./backend/src
        target: /app/src
        read_only: true
    env_file:
      - backend/variables.env
    ports:
      - "5000:5000"