#run 'docker compose up --build' to show changes by rebuilding images
services:
  flask:
    build: ./backend
    volumes:
      - type: bind
        source: ./backend/src
        target: /app/src
        read_only: true
    env_file:
      - backend/variables.env
    ports:
      - "5000:5000"
    depends_on:
      - redis

  frontend:
    build: ./frontend
    volumes:
      - type: bind
        source: ./frontend/src
        target: /app/src
        # read_only: true
    command: sh -c "rm -rf node_modules/.vite/deps && npx vite --host 0.0.0.0"
    ports:
     - "5173:5173"

  # simple_worker:
  #   build: './backend/simple_worker'
  #   volumes:
  #     - type: bind
  #       source: ./backend/simple_worker
  #       target: /simple_worker/src
  #       read_only: true
  #   user: nobody
  #   depends_on:
  #     - redis
  #     - flask

  redis:
    image: 'redis:4-alpine'
    ports:
      - '6379:6379'
    